export const FETCH_NOTIFICATIONS_REQUEST = "FETCH_NOTIFICATIONS_REQUEST"
export const FETCH_NOTIFICATIONS_SUCCEEDED = "FETCH_NOTIFICATIONS_SUCCEEDED"

export const fetchNotifications = () => {
    return { type: FETCH_NOTIFICATIONS_REQUEST }
}